# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 11:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newslink',
            options={'get_latest_by': 'pub_date', 'ordering': ['-pub_date'], 'verbose_name': 'news article'},
        ),
        migrations.AlterModelOptions(
            name='startup',
            options={'get_latest_by': 'founded_date', 'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
    ]
